// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tinder_1.DataBase;

#nullable disable

namespace tinder_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tinder_1.Models.BadHabitsAttitude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("BadHabitsAttitudes", "public");
                });

            modelBuilder.Entity("tinder_1.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Cities", "public");
                });

            modelBuilder.Entity("tinder_1.Models.FilmGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("FilmGenres", "public");
                });

            modelBuilder.Entity("tinder_1.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Genders", "public");
                });

            modelBuilder.Entity("tinder_1.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Hobbies", "public");
                });

            modelBuilder.Entity("tinder_1.Models.MusicGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("MusicGenres", "public");
                });

            modelBuilder.Entity("tinder_1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("tinder_1.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AboutMe");

                    b.Property<int?>("BadHabitsAttitudeId")
                        .HasColumnType("integer")
                        .HasColumnName("BadHabitsAttitudeId");

                    b.Property<int>("BadHabitsAttitudeId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("BirthDate");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("CityId");

                    b.Property<int>("CityId1")
                        .HasColumnType("integer");

                    b.Property<int?>("FilmGenreId")
                        .HasColumnType("integer")
                        .HasColumnName("FilmGenreId");

                    b.Property<int>("FilmGenreId1")
                        .HasColumnType("integer");

                    b.Property<int?>("GenderId")
                        .HasColumnType("integer")
                        .HasColumnName("GenderId");

                    b.Property<int>("GenderId1")
                        .HasColumnType("integer");

                    b.Property<int?>("HobbyId")
                        .HasColumnType("integer")
                        .HasColumnName("HobbyId");

                    b.Property<int>("HobbyId1")
                        .HasColumnType("integer");

                    b.Property<int?>("MusicGenreId")
                        .HasColumnType("integer")
                        .HasColumnName("MusicGenreId");

                    b.Property<int>("MusicGenreId1")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("PhotoPath");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.Property<int>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadHabitsAttitudeId");

                    b.HasIndex("BadHabitsAttitudeId1");

                    b.HasIndex("CityId");

                    b.HasIndex("CityId1");

                    b.HasIndex("FilmGenreId");

                    b.HasIndex("FilmGenreId1");

                    b.HasIndex("GenderId");

                    b.HasIndex("GenderId1");

                    b.HasIndex("HobbyId");

                    b.HasIndex("HobbyId1");

                    b.HasIndex("MusicGenreId");

                    b.HasIndex("MusicGenreId1");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("UserProfiles", "public");
                });

            modelBuilder.Entity("tinder_1.Models.UserProfile", b =>
                {
                    b.HasOne("tinder_1.Models.BadHabitsAttitude", null)
                        .WithMany()
                        .HasForeignKey("BadHabitsAttitudeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tinder_1.Models.BadHabitsAttitude", "BadHabitsAttitude")
                        .WithMany()
                        .HasForeignKey("BadHabitsAttitudeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tinder_1.Models.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tinder_1.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tinder_1.Models.FilmGenre", null)
                        .WithMany()
                        .HasForeignKey("FilmGenreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tinder_1.Models.FilmGenre", "FilmGenre")
                        .WithMany()
                        .HasForeignKey("FilmGenreId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tinder_1.Models.Gender", null)
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tinder_1.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tinder_1.Models.Hobby", null)
                        .WithMany()
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tinder_1.Models.Hobby", "Hobby")
                        .WithMany()
                        .HasForeignKey("HobbyId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tinder_1.Models.MusicGenre", null)
                        .WithMany()
                        .HasForeignKey("MusicGenreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tinder_1.Models.MusicGenre", "MusicGenre")
                        .WithMany()
                        .HasForeignKey("MusicGenreId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tinder_1.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tinder_1.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadHabitsAttitude");

                    b.Navigation("City");

                    b.Navigation("FilmGenre");

                    b.Navigation("Gender");

                    b.Navigation("Hobby");

                    b.Navigation("MusicGenre");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
